### ISSUE TITLE
Clipboard command no longer working

### ISSUE THREAD

**Issue by tophertimzen** [MythicAgents/apfell#6]
Upon upgrading to `v2.3.7` of Mythic and the latest apfell, the `clipboard` command no longer works.

`help clipboard` shows

```
Usage Help: clipboard [data]

Description: Get all the types of contents on the clipboard, return specific types, or set the contents of the clipboard. Root has no clipboard!
Command Attributes: {
  "spawn_and_injectable": false,
  "supported_os": [],
  "builtin": false,
  "suggested_command": false,
  "load_only": false,
  "filter_by_build_parameter": {}
}

Parameter Group: "read"
  Name: Clipboard-Types
    Description: Types of clipboard data to retrieve, defaults to public.utf8-plain-text
    Type: Array
    Default Value: ["public.utf8-plain-text"]
    Required: False

Parameter Group: "write"
  Name: data
    Description: Data to put on the clipboard
    Type: String
    Default Value: 
    Required: False
```

and trying to run `clipboard read` does not work. Not does doing `clipboard read public.utf8-plain-text` which should be the default value.

clipboard read

`TypeError: undefined is not an object (evaluating 'parsed_params['types'].length')`

I cannot get it to work with any Value, including the default. I get the same TYpeError.

**Comment by its-a-feature** [comment]
Yup! You're exactly right, there was something seriously borked with that command. I just made an update to the main branch that should fix it with updates to the browser script, the agent command, and the python files associated with it. You should now be able to actually do:
`clipboard -read` or `clipboard -data "set some data here to the clipboard"`. 
To pull in these updates simply do: `sudo ./mythic-cli install github https://github.com/MythicAgents/apfell -f` and then on existing callback, pull in the latest agent code with `load clipboard`. You should then be good to go. 
For what it's worth, I also pushed an update to the new UI of Mythic with this update because I noticed that if the clipboard data spanned multiple lines that the text would overflow in the virtualized table, so that should be fixed now too. To get that fix, you'll need to pull down the latest Mythic code (only the code in the mythic-react-docker folder should have updated)

**Comment by tophertimzen** [comment]
Can confirm it works now!

I am looking into ways to also auto-monitor the clipboard for any modifications, not just at the time of invocation of the clipboard command. Any ideas there, @its-a-feature? Closing issue either way as it is resolved. :)
